"""
AssemblyAI supported language codes for manual transcription.

Source: TranscriptLanguageCode in AssemblyAI OpenAPI / supported-languages docs.
Total manual language options: 103
"""

TRANSCRIPT_LANGUAGE_CODES = [
    "en", "en_au", "en_uk", "en_us", "es", "fr", "de", "de_ch", "it", "pt",
    "nl", "af", "sq", "am", "ar", "hy", "as", "az", "ba", "eu",
    "be", "bn", "bs", "br", "bg", "my", "ca", "zh", "hr", "cs",
    "da", "et", "fo", "fi", "gl", "ka", "el", "gu", "ht", "ha",
    "haw", "he", "hi", "hu", "is", "id", "ja", "jw", "kn", "kk",
    "km", "ko", "lo", "la", "lv", "ln", "lt", "lb", "mk", "mg",
    "ms", "ml", "mt", "mi", "mr", "mn", "ne", "no", "nn", "oc",
    "pa", "ps", "fa", "pl", "ro", "ru", "sa", "sr", "sn", "sd",
    "si", "sk", "sl", "so", "su", "sw", "sv", "tl", "tg", "ta",
    "tt", "te", "th", "bo", "tr", "tk", "uk", "ur", "uz", "vi",
    "cy", "yi", "yo",
]

DISPLAY_NAME_OVERRIDES = {
    "de_ch": "German (Swiss)",
    "en": "English (Global)",
    "en_au": "English (Australia)",
    "en_uk": "English (UK)",
    "en_us": "English (US)",
    "fa": "Persian (Farsi)",
    "he": "Hebrew",
    "jw": "Javanese",
    "mi": "Maori",
    "my": "Burmese",
    "nn": "Norwegian Nynorsk",
    "no": "Norwegian",
    "pt": "Portuguese",
    "tl": "Tagalog",
    "zh": "Chinese (Mandarin)",
}


def language_display_name(code: str) -> str:
    """Return a human-readable language name for a code."""
    if code in DISPLAY_NAME_OVERRIDES:
        return DISPLAY_NAME_OVERRIDES[code]
    base = code.split("_")[0]
    # Fallback for unknown codes
    return code.replace("_", " ").title()


def build_manual_language_choices() -> list[tuple[str, str]]:
    """Build (label, code) pairs for UI dropdowns."""
    return [
        ("English (Global) (en)", "en"),
        ("English (Australia) (en_au)", "en_au"),
        ("English (UK) (en_uk)", "en_uk"),
        ("English (US) (en_us)", "en_us"),
        ("Spanish (es)", "es"),
        ("French (fr)", "fr"),
        ("German (de)", "de"),
        ("German (Swiss) (de_ch)", "de_ch"),
        ("Italian (it)", "it"),
        ("Portuguese (pt)", "pt"),
        ("Dutch (nl)", "nl"),
        ("Afrikaans (af)", "af"),
        ("Albanian (sq)", "sq"),
        ("Amharic (am)", "am"),
        ("Arabic (ar)", "ar"),
        ("Armenian (hy)", "hy"),
        ("Assamese (as)", "as"),
        ("Azerbaijani (az)", "az"),
        ("Bashkir (ba)", "ba"),
        ("Basque (eu)", "eu"),
        ("Belarusian (be)", "be"),
        ("Bengali (bn)", "bn"),
        ("Bosnian (bs)", "bs"),
        ("Breton (br)", "br"),
        ("Bulgarian (bg)", "bg"),
        ("Burmese (my)", "my"),
        ("Catalan (ca)", "ca"),
        ("Chinese (Mandarin) (zh)", "zh"),
        ("Croatian (hr)", "hr"),
        ("Czech (cs)", "cs"),
        ("Danish (da)", "da"),
        ("Estonian (et)", "et"),
        ("Faroese (fo)", "fo"),
        ("Finnish (fi)", "fi"),
        ("Galician (gl)", "gl"),
        ("Georgian (ka)", "ka"),
        ("Greek (el)", "el"),
        ("Gujarati (gu)", "gu"),
        ("Haitian Creole (ht)", "ht"),
        ("Hausa (ha)", "ha"),
        ("Hawaiian (haw)", "haw"),
        ("Hebrew (he)", "he"),
        ("Hindi (hi)", "hi"),
        ("Hungarian (hu)", "hu"),
        ("Icelandic (is)", "is"),
        ("Indonesian (id)", "id"),
        ("Japanese (ja)", "ja"),
        ("Javanese (jw)", "jw"),
        ("Kannada (kn)", "kn"),
        ("Kazakh (kk)", "kk"),
        ("Khmer (km)", "km"),
        ("Korean (ko)", "ko"),
        ("Lao (lo)", "lo"),
        ("Latin (la)", "la"),
        ("Latvian (lv)", "lv"),
        ("Lingala (ln)", "ln"),
        ("Lithuanian (lt)", "lt"),
        ("Luxembourgish (lb)", "lb"),
        ("Macedonian (mk)", "mk"),
        ("Malagasy (mg)", "mg"),
        ("Malay (ms)", "ms"),
        ("Malayalam (ml)", "ml"),
        ("Maltese (mt)", "mt"),
        ("Maori (mi)", "mi"),
        ("Marathi (mr)", "mr"),
        ("Mongolian (mn)", "mn"),
        ("Nepali (ne)", "ne"),
        ("Norwegian (no)", "no"),
        ("Norwegian Nynorsk (nn)", "nn"),
        ("Occitan (oc)", "oc"),
        ("Punjabi (pa)", "pa"),
        ("Pashto (ps)", "ps"),
        ("Persian (Farsi) (fa)", "fa"),
        ("Polish (pl)", "pl"),
        ("Romanian (ro)", "ro"),
        ("Russian (ru)", "ru"),
        ("Sanskrit (sa)", "sa"),
        ("Serbian (sr)", "sr"),
        ("Shona (sn)", "sn"),
        ("Sindhi (sd)", "sd"),
        ("Sinhala (si)", "si"),
        ("Slovak (sk)", "sk"),
        ("Slovenian (sl)", "sl"),
        ("Somali (so)", "so"),
        ("Sundanese (su)", "su"),
        ("Swahili (sw)", "sw"),
        ("Swedish (sv)", "sv"),
        ("Tagalog (tl)", "tl"),
        ("Tajik (tg)", "tg"),
        ("Tamil (ta)", "ta"),
        ("Tatar (tt)", "tt"),
        ("Telugu (te)", "te"),
        ("Thai (th)", "th"),
        ("Tibetan (bo)", "bo"),
        ("Turkish (tr)", "tr"),
        ("Turkmen (tk)", "tk"),
        ("Ukrainian (uk)", "uk"),
        ("Urdu (ur)", "ur"),
        ("Uzbek (uz)", "uz"),
        ("Vietnamese (vi)", "vi"),
        ("Welsh (cy)", "cy"),
        ("Yiddish (yi)", "yi"),
        ("Yoruba (yo)", "yo"),
    ]


MANUAL_LANGUAGE_CHOICES = build_manual_language_choices()
